#!/bin/bash
set -e

echo "Alternative deployment methods for AstroShield UDL Integration"
echo "============================================================="
echo ""
echo "The deployment package has been created: udl_integration_deploy.tar.gz"
echo ""
echo "Since we're having SSH connectivity issues, here are alternative deployment methods:"
echo ""
echo "1. Manual Transfer Method:"
echo "   - Download the deployment package manually from this machine"
echo "   - Connect to the EC2 instance using your own SSH client or the AWS Console"
echo "   - Upload the package to the EC2 instance"
echo "   - Extract with: mkdir -p ~/udl_integration && tar -xzf ~/udl_integration_deploy.tar.gz -C ~/udl_integration"
echo "   - Install with: cd ~/udl_integration && chmod +x setup.sh && ./setup.sh"
echo ""
echo "2. AWS CLI Transfer Method (if AWS CLI is configured):"
echo "   # Upload using AWS S3 as intermediate storage"
echo "   aws s3 cp udl_integration_deploy.tar.gz s3://your-bucket-name/"
echo "   # Then on the EC2 instance:"
echo "   aws s3 cp s3://your-bucket-name/udl_integration_deploy.tar.gz ~/"
echo "   mkdir -p ~/udl_integration && tar -xzf ~/udl_integration_deploy.tar.gz -C ~/udl_integration"
echo "   cd ~/udl_integration && chmod +x setup.sh && ./setup.sh"
echo ""
echo "3. Web Transfer Method:"
echo "   # Host the file on a temporary web server"
echo "   python -m http.server 8000"
echo "   # Then on the EC2 instance:"
echo "   curl http://your-ip:8000/udl_integration_deploy.tar.gz -o ~/udl_integration_deploy.tar.gz"
echo "   mkdir -p ~/udl_integration && tar -xzf ~/udl_integration_deploy.tar.gz -C ~/udl_integration"
echo "   cd ~/udl_integration && chmod +x setup.sh && ./setup.sh"
echo ""
echo "4. The package is ready for deployment via any available method that works for your environment."
echo ""
echo "The UDL Integration can now be deployed to the target EC2 instance using any of these methods."
echo "==================================================================" 